### ISSUE TITLE
Enum serialization issue causes confluence API to not function properly 

### ISSUE THREAD

**Issue by peter-szabo** [dapplo/Dapplo.HttpExtensions#15]
Hello,

I would like to use the Dapplo.Confluence library to insert entries into confluence automatically.
The current implementation of the enum serialization only works when querying confluence, but does not work when trying to insert new items to it.
I created a pull request with a proposed fix, please take a look.

Greetings,
Peter

**Comment by Lakritzator** [comment]
Thanks for reporting this, the solution in your pull-request would fix the confluence issue but is to specific. I made a more generic fix.

**Comment by Lakritzator** [comment]
The fix is in 0.8.25, will update the confluence library with the fix.
