### ISSUE TITLE
Cannot build an application that uses this under linux / .net core 3.0

### ISSUE THREAD

**Issue by mjharwood** [dapplo/Dapplo.HttpExtensions#16]
I ran into this problem with an application that uses Dapplo.Confluence

The build fails with:

```
 error NETSDK1073: The FrameworkReference 'Microsoft.WindowsDesktop.App.WindowsForms' was not recognized.
```
so far I've found:
* HttpExtensions uses Bitmap from System.Drawing.Imaging
* HttpExtensions.OAuth uses WinForms

**Comment by Lakritzator** [comment]
I think the main issue here is that the Dapplo.Confluence package für dotnet core 3.0 references the HttpExtensions for dotnet core 3.0 which automatically uses Windows code. I'm not sure how to differentiate when building for Linux, as the target "framework" alone is not sufficient.

Thanks for reporting this, I hope to get some time for this in the coming days.

**Comment by mjharwood** [comment]
As far as I can tell, you need to build & test it twice (once for linux, once for windows) to find any platform specific issues. The release package can then be built on just one once any issues are resolved.

Here's the dependency: Dapplo.Confluence, references Dapplo.HttpExtensions.OAuth which references Dapplo.Windows

I was testing with an alpine linux docker  image, under windows 10 if that helps.

**Comment by Lakritzator** [comment]
To my knowledge this should have been solved, I moved all the dependencies to different packages to at least have the basic functionality (without bitmaps) available within Linux or other platforms.
